apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-academy-webapp
  labels:
    app: devops-academy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-academy
  template:
    metadata:
      labels:
        app: devops-academy
    spec:
        containers:
          - name: webapp
            image: <your-dockerhub-username>/tesco:latest
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: example
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-academy-service
spec:
  type: NodePort
  selector:
    app: devops-academy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036

